import React, { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Bell,
  CheckCheck,
  Sparkles,
  KeyRound,
  Zap,
  AlertTriangle,
  CheckCircle2,
  Clock,
} from 'lucide-react'
import { Link } from 'react-router-dom'

const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif_1',
    title: 'Research Pipeline Completed',
    description: 'Task tsk_9f83a1b2 ("Agentic AI architectures") finished in 4.2s with 18 verified citations.',
    time: '10 mins ago',
    type: 'TASK',
    read: false,
    link: '/dashboard/tasks/tsk_9f83a1b2',
  },
  {
    id: 'notif_2',
    title: 'New API Key Created',
    description: 'API key "Production Worker Key" was successfully generated by Yash Tailor.',
    time: '45 mins ago',
    type: 'SECURITY',
    read: false,
    link: '/dashboard/api-keys',
  },
  {
    id: 'notif_3',
    title: 'Monthly Credits Refilled',
    description: '10,000 credits added to your workspace for the Developer Pro billing cycle.',
    time: '1 day ago',
    type: 'BILLING',
    read: true,
    link: '/dashboard/billing',
  },
  {
    id: 'notif_4',
    title: 'High Concurrency Alert',
    description: 'Parallel worker concurrency peaked at 8 simultaneous search threads.',
    time: '2 days ago',
    type: 'SYSTEM',
    read: true,
    link: '/dashboard/usage',
  },
]

export default function Notifications() {
  const [notifications, setNotifications] = useState(INITIAL_NOTIFICATIONS)
  const [filter, setFilter] = useState('ALL')

  const handleMarkAllRead = () => {
    setNotifications(notifications.map((n) => ({ ...n, read: true })))
  }

  const filtered = notifications.filter((n) => {
    if (filter === 'UNREAD') return !n.read
    return true
  })

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-xl md:text-2xl font-bold tracking-tight">Notification Center</h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            Real-time pipeline lifecycle events, security triggers, and billing updates.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="xs"
            onClick={handleMarkAllRead}
            className="rounded-lg h-8 text-xs gap-1"
          >
            <CheckCheck className="h-3 w-3" /> Mark All as Read
          </Button>
        </div>
      </div>

      {/* Notifications List */}
      <Card className="rounded-xl border-border bg-card shadow-xs overflow-hidden">
        <CardHeader className="flex flex-row items-center justify-between py-3 px-4 border-b border-border">
          <div className="flex items-center gap-2">
            <Button
              variant={filter === 'ALL' ? 'default' : 'ghost'}
              size="xs"
              onClick={() => setFilter('ALL')}
              className="rounded-md text-[11px] h-6 px-2.5"
            >
              All Events
            </Button>
            <Button
              variant={filter === 'UNREAD' ? 'default' : 'ghost'}
              size="xs"
              onClick={() => setFilter('UNREAD')}
              className="rounded-md text-[11px] h-6 px-2.5"
            >
              Unread Only
            </Button>
          </div>

          <Badge variant="outline" className="font-mono text-[10px] px-1.5 py-0">
            {notifications.filter((n) => !n.read).length} Unread
          </Badge>
        </CardHeader>

        <CardContent className="p-0 divide-y divide-border">
          {filtered.length === 0 ? (
            <div className="py-8 text-center text-xs text-muted-foreground">
              No notifications to display.
            </div>
          ) : (
            filtered.map((n) => (
              <div
                key={n.id}
                className={`p-3.5 flex items-start justify-between gap-3 transition-colors hover:bg-muted/30 ${
                  !n.read ? 'bg-primary/5' : ''
                }`}
              >
                <div className="flex items-start gap-3">
                  <div
                    className={`p-2 rounded-lg shrink-0 mt-0.5 ${
                      n.type === 'TASK'
                        ? 'bg-primary/10 text-primary'
                        : n.type === 'SECURITY'
                        ? 'bg-amber-500/10 text-amber-400'
                        : n.type === 'BILLING'
                        ? 'bg-emerald-500/10 text-emerald-400'
                        : 'bg-violet-500/10 text-violet-400'
                    }`}
                  >
                    {n.type === 'TASK' && <Sparkles className="h-3.5 w-3.5" />}
                    {n.type === 'SECURITY' && <KeyRound className="h-3.5 w-3.5" />}
                    {n.type === 'BILLING' && <Zap className="h-3.5 w-3.5" />}
                    {n.type === 'SYSTEM' && <AlertTriangle className="h-3.5 w-3.5" />}
                  </div>

                  <div className="space-y-0.5">
                    <div className="flex items-center gap-2">
                      <h4 className="text-xs font-semibold text-foreground">{n.title}</h4>
                      {!n.read && (
                        <span className="w-1.5 h-1.5 rounded-full bg-primary" />
                      )}
                    </div>
                    <p className="text-[11px] text-muted-foreground leading-relaxed">{n.description}</p>
                    <span className="text-[10px] text-muted-foreground font-mono inline-block mt-0.5">
                      {n.time}
                    </span>
                  </div>
                </div>

                <Button asChild variant="ghost" size="xs" className="rounded-md shrink-0 h-6 text-[11px] hover:text-primary">
                  <Link to={n.link}>View</Link>
                </Button>
              </div>
            ))
          )}
        </CardContent>
      </Card>
    </div>
  )
}
