# coding: utf-8

"""
    Sequential AI Task API

    Enterprise-grade API for deep research and synthesis tasks.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sequential_ai.models.task_v2_execution import TaskV2Execution
from sequential_ai.models.task_v2_input import TaskV2Input
from sequential_ai.models.task_v2_output import TaskV2Output
from sequential_ai.models.task_v2_sources_inner import TaskV2SourcesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TaskV2(BaseModel):
    """
    TaskV2
    """ # noqa: E501
    id: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    input: Optional[TaskV2Input] = None
    execution: Optional[TaskV2Execution] = None
    output: Optional[TaskV2Output] = None
    sources: Optional[List[TaskV2SourcesInner]] = None
    __properties: ClassVar[List[str]] = ["id", "status", "input", "execution", "output", "sources"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PENDING', 'PLANNING', 'RUNNING', 'SYNTHESIZING', 'COMPLETED', 'FAILED']):
            raise ValueError("must be one of enum values ('PENDING', 'PLANNING', 'RUNNING', 'SYNTHESIZING', 'COMPLETED', 'FAILED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['input'] = self.input.to_dict()
        # override the default output from pydantic by calling `to_dict()` of execution
        if self.execution:
            _dict['execution'] = self.execution.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['output'] = self.output.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sources (list)
        _items = []
        if self.sources:
            for _item_sources in self.sources:
                if _item_sources:
                    _items.append(_item_sources.to_dict())
            _dict['sources'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "input": TaskV2Input.from_dict(obj["input"]) if obj.get("input") is not None else None,
            "execution": TaskV2Execution.from_dict(obj["execution"]) if obj.get("execution") is not None else None,
            "output": TaskV2Output.from_dict(obj["output"]) if obj.get("output") is not None else None,
            "sources": [TaskV2SourcesInner.from_dict(_item) for _item in obj["sources"]] if obj.get("sources") is not None else None
        })
        return _obj


