# coding: utf-8

# flake8: noqa

"""
    Sequential AI Task API

    Enterprise-grade API for deep research and synthesis tasks.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "TaskV2",
    "TaskV2Execution",
    "TaskV2Input",
    "TaskV2Output",
    "TaskV2SourcesInner",
    "TasksPostRequest",
]

# import apis into sdk package
from sequential_ai.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from sequential_ai.api_response import ApiResponse as ApiResponse
from sequential_ai.api_client import ApiClient as ApiClient
from sequential_ai.configuration import Configuration as Configuration
from sequential_ai.exceptions import OpenApiException as OpenApiException
from sequential_ai.exceptions import ApiTypeError as ApiTypeError
from sequential_ai.exceptions import ApiValueError as ApiValueError
from sequential_ai.exceptions import ApiKeyError as ApiKeyError
from sequential_ai.exceptions import ApiAttributeError as ApiAttributeError
from sequential_ai.exceptions import ApiException as ApiException

# import models into sdk package
from sequential_ai.models.task_v2 import TaskV2 as TaskV2
from sequential_ai.models.task_v2_execution import TaskV2Execution as TaskV2Execution
from sequential_ai.models.task_v2_input import TaskV2Input as TaskV2Input
from sequential_ai.models.task_v2_output import TaskV2Output as TaskV2Output
from sequential_ai.models.task_v2_sources_inner import TaskV2SourcesInner as TaskV2SourcesInner
from sequential_ai.models.tasks_post_request import TasksPostRequest as TasksPostRequest

