/**
 * Sequential AI Task API
 * Enterprise-grade API for deep research and synthesis tasks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TaskV2Execution {
    'workerRuns'?: Array<object>;
    'metrics'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workerRuns",
            "baseName": "workerRuns",
            "type": "Array<object>"
        },
        {
            "name": "metrics",
            "baseName": "metrics",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return TaskV2Execution.attributeTypeMap;
    }
}

