/**
 * Sequential AI Task API
 * Enterprise-grade API for deep research and synthesis tasks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TaskV2Execution } from './taskV2Execution';
import { TaskV2Input } from './taskV2Input';
import { TaskV2Output } from './taskV2Output';
import { TaskV2SourcesInner } from './taskV2SourcesInner';

export class TaskV2 {
    'id'?: string;
    'status'?: TaskV2.StatusEnum;
    'input'?: TaskV2Input;
    'execution'?: TaskV2Execution;
    'output'?: TaskV2Output;
    'sources'?: Array<TaskV2SourcesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskV2.StatusEnum"
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "TaskV2Input"
        },
        {
            "name": "execution",
            "baseName": "execution",
            "type": "TaskV2Execution"
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "TaskV2Output"
        },
        {
            "name": "sources",
            "baseName": "sources",
            "type": "Array<TaskV2SourcesInner>"
        }    ];

    static getAttributeTypeMap() {
        return TaskV2.attributeTypeMap;
    }
}

export namespace TaskV2 {
    export enum StatusEnum {
        Pending = <any> 'PENDING',
        Planning = <any> 'PLANNING',
        Running = <any> 'RUNNING',
        Synthesizing = <any> 'SYNTHESIZING',
        Completed = <any> 'COMPLETED',
        Failed = <any> 'FAILED'
    }
}
