/**
 * Sequential AI Task API
 * Enterprise-grade API for deep research and synthesis tasks.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TasksPostRequest {
    /**
    * The research query
    */
    'query': string;
    'mode'?: TasksPostRequest.ModeEnum = TasksPostRequest.ModeEnum.Fast;
    /**
    * JSON Schema Draft-07 to validate the extracted output.
    */
    'taskSpec'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "TasksPostRequest.ModeEnum"
        },
        {
            "name": "taskSpec",
            "baseName": "taskSpec",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return TasksPostRequest.attributeTypeMap;
    }
}

export namespace TasksPostRequest {
    export enum ModeEnum {
        Fast = <any> 'FAST',
        Standard = <any> 'STANDARD',
        Deep = <any> 'DEEP'
    }
}
