# coding: utf-8

"""
    Sequential AI Task API

    Enterprise-grade API for deep research and synthesis tasks.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sequential_ai.models.task_v2_output import TaskV2Output

class TestTaskV2Output(unittest.TestCase):
    """TaskV2Output unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskV2Output:
        """Test TaskV2Output
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskV2Output`
        """
        model = TaskV2Output()
        if include_optional:
            return TaskV2Output(
                answer = '',
                data = sequential_ai.models.data.data()
            )
        else:
            return TaskV2Output(
        )
        """

    def testTaskV2Output(self):
        """Test TaskV2Output"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
