# coding: utf-8

"""
    Sequential AI Task API

    Enterprise-grade API for deep research and synthesis tasks.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sequential_ai.models.task_v2_execution import TaskV2Execution

class TestTaskV2Execution(unittest.TestCase):
    """TaskV2Execution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskV2Execution:
        """Test TaskV2Execution
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskV2Execution`
        """
        model = TaskV2Execution()
        if include_optional:
            return TaskV2Execution(
                worker_runs = [
                    None
                    ],
                metrics = sequential_ai.models.metrics.metrics()
            )
        else:
            return TaskV2Execution(
        )
        """

    def testTaskV2Execution(self):
        """Test TaskV2Execution"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
