# coding: utf-8

"""
    Sequential AI Task API

    Enterprise-grade API for deep research and synthesis tasks.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sequential_ai.models.task_v2 import TaskV2

class TestTaskV2(unittest.TestCase):
    """TaskV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskV2:
        """Test TaskV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskV2`
        """
        model = TaskV2()
        if include_optional:
            return TaskV2(
                id = '',
                status = 'PENDING',
                input = sequential_ai.models.task_v2_input.TaskV2_input(
                    query = '', 
                    mode = '', 
                    task_spec = sequential_ai.models.task_spec.taskSpec(), ),
                execution = sequential_ai.models.task_v2_execution.TaskV2_execution(
                    worker_runs = [
                        None
                        ], 
                    metrics = sequential_ai.models.metrics.metrics(), ),
                output = sequential_ai.models.task_v2_output.TaskV2_output(
                    answer = '', 
                    data = sequential_ai.models.data.data(), ),
                sources = [
                    sequential_ai.models.task_v2_sources_inner.TaskV2_sources_inner(
                        id = '', 
                        url = '', 
                        domain = '', )
                    ]
            )
        else:
            return TaskV2(
        )
        """

    def testTaskV2(self):
        """Test TaskV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
