# coding: utf-8

"""
    Sequential AI Task API

    Enterprise-grade API for deep research and synthesis tasks.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sequential_ai.models.task_v2_sources_inner import TaskV2SourcesInner

class TestTaskV2SourcesInner(unittest.TestCase):
    """TaskV2SourcesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskV2SourcesInner:
        """Test TaskV2SourcesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskV2SourcesInner`
        """
        model = TaskV2SourcesInner()
        if include_optional:
            return TaskV2SourcesInner(
                id = '',
                url = '',
                domain = ''
            )
        else:
            return TaskV2SourcesInner(
        )
        """

    def testTaskV2SourcesInner(self):
        """Test TaskV2SourcesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
