# coding: utf-8

"""
    Sequential AI Task API

    Enterprise-grade API for deep research and synthesis tasks.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sequential_ai.models.tasks_post_request import TasksPostRequest

class TestTasksPostRequest(unittest.TestCase):
    """TasksPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TasksPostRequest:
        """Test TasksPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TasksPostRequest`
        """
        model = TasksPostRequest()
        if include_optional:
            return TasksPostRequest(
                query = '',
                mode = 'FAST',
                task_spec = None
            )
        else:
            return TasksPostRequest(
                query = '',
        )
        """

    def testTasksPostRequest(self):
        """Test TasksPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
