# coding: utf-8

"""
    Sequential AI Task API

    Enterprise-grade API for deep research and synthesis tasks.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sequential_ai.models.task_v2_input import TaskV2Input

class TestTaskV2Input(unittest.TestCase):
    """TaskV2Input unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskV2Input:
        """Test TaskV2Input
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskV2Input`
        """
        model = TaskV2Input()
        if include_optional:
            return TaskV2Input(
                query = '',
                mode = '',
                task_spec = sequential_ai.models.task_spec.taskSpec()
            )
        else:
            return TaskV2Input(
        )
        """

    def testTaskV2Input(self):
        """Test TaskV2Input"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
